name: MedReminder-backend Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    
    - name: Set up config
      uses: jsdaniell/create-json@v1.2.1
      id: create-json
      with:
        name: "test_config.json"
        json: ${{ secrets.TEST_CONFIG_JSON }}
        dir: "data/"
    
    - name: Build
      run: mvn --batch-mode -DskipTests package
      
    - name: Test
      run: mvn --batch-mode test
      
    - name: Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: 'Unit Test Report'
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

